name: Waka Readme

on:
  schedule:
    # runs at every 12AM UTC
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_PROJECTS: false
          SHOW_TIMEZONE: false
          SHOW_SHORT_INFO: false
          SHOW_LOC_CHART: false
          SHOW_UPDATED_DATE: false
          SHOW_LANGUAGE_PER_REPO: false
      - name: Place Counter
        run: |
          echo "\n![](https://hit.yhype.me/github/profile?account_id=96577465)" >> README.md
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Place counter"
          git push
